### ISSUE TITLE
The "img_pil = crop_white_side(get_image(file_name, -1)[0], d=10)"  used on SOTA dataset is wrong? 

### ISSUE THREAD

**Issue by Yang-Chenghao** [XLearning-SCU/2021-IJCV-YOLY#2]
The crop_white_side is used for gt_img preprocess when we run dehazing.py on SOTA dataset. However, the hazy_img is processed by the img_crop, which makes the hazy_img bigger than the gt_img.

**Comment by XLearning-SCU** [comment]
I am sorry to reply you so late and many thanks to your suggestions. I have fixed this problem and upload the fixed version.
