### ISSUE TITLE
问个问题？

### ISSUE THREAD

**Issue by mengxzh15** [XLearning-SCU/2021-IJCV-YOLY#4]
这篇文章和zero-shot learning dehazing有什么不同吗？感觉一个思路，不过改了改损失而已。

**Comment by XLearning-SCU** [comment]
不好意思最近才看到您的消息。YOLY和ZID主要有两个方面的不同，一个是在网络结构上，ZID使用U-Net型的结构来提取多尺度特征以恢复图像，但是在实际运行过程中我们发现下采样的过程让网络损失了一定的细节使得恢复的J、T等较为模糊，因此不同于ZID的多尺度网络，YOLY采用了non-degenerate的架构，保留了恢复图像的细节。同时在损失函数上，取消了在T上的约束以保留细节、采用了CAPloss以解决DCP loss导致的在部分图片上过曝的问题。
